"""empty message

Revision ID: 04f428d61777
Revises: bd5eb1cacdd6
Create Date: 2021-05-14 10:31:57.912859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f428d61777'
down_revision = 'bd5eb1cacdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('form', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'form')
    # ### end Alembic commands ###
