"""empty message

Revision ID: 475312f159c9
Revises: 
Create Date: 2021-05-14 00:50:04.088804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475312f159c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('min_quantity', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('max_quantity', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('reorder_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'reorder_level')
    op.drop_column('inventory', 'max_quantity')
    op.drop_column('inventory', 'min_quantity')
    # ### end Alembic commands ###
