"""empty message

Revision ID: 4e4a06e65ef5
Revises: 475312f159c9
Create Date: 2021-05-14 01:04:45.351519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4a06e65ef5'
down_revision = '475312f159c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('meds', sa.JSON(), nullable=True))
    op.add_column('appointments', sa.Column('record_form', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'record_form')
    op.drop_column('appointments', 'meds')
    # ### end Alembic commands ###
