"""empty message

Revision ID: bd5eb1cacdd6
Revises: 50d243d20423
Create Date: 2021-05-14 02:07:53.384205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd5eb1cacdd6'
down_revision = '50d243d20423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('receive_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('inventory_ibfk_1', 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'expiry_date')
    op.drop_column('inventory', 'status_id')
    op.drop_column('inventory', 'quantity')
    op.drop_column('inventory', 'receive_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('receive_date', mysql.DATETIME(), nullable=True))
    op.add_column('inventory', sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('expiry_date', mysql.DATETIME(), nullable=True))
    op.create_foreign_key('inventory_ibfk_1', 'inventory', 'status', ['status_id'], ['id'])
    op.drop_table('items')
    # ### end Alembic commands ###
